Feat: Detect Associated PR
ubiquity/bounty-bot pull request #257
Opened 2023-04-11 15:20 UTC by Steveantor

Resolves #243

2023-04-16 12:44 UTC, Steveantor commented on src/helpers/parser.ts
> +    const devForm = dom.querySelector("[data-target='create-branch.developmentForm']") as HTMLElement;
I can confirm that there's no standard REST API for that

2023-04-17 08:01 UTC, rndquu commented on src/helpers/parser.ts
> +    const devForm = dom.querySelector("[data-target='create-branch.developmentForm']") as HTMLElement;
Yes, unfortunately there is no standard API for getting linked PRs for an issue

2023-04-17 08:47 UTC, 0xcodercrane requested changes

2023-04-17 08:47 UTC, 0xcodercrane commented on src/utils/github.ts
> +// import { AxiosResponseHeaders } from "axios";
lets remove!

2023-04-24 05:59 UTC, pavlovcik approved these changes
Not sure how to test this but the code looks fine. @0xcodercrane please merge this in as soon as you re-review.

2023-04-24 14:03 UTC, 0xcodercrane commented
> Not sure how to test this but the code looks fine. @0xcodercrane please merge this in as soon as you re-review.

I will quickly take a deep dive on how to get the linked PR for the issue and merge it

2023-04-24 14:48 UTC, merged